spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # validate
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format sql: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always